### ISSUE TITLE
Rename getting started vigniette

### ISSUE THREAD

**Issue by pawelru** [pharmaverse/sdtmchecks#1]
If you rename your getting started vignette into the package name it would be automatically detected by `pkgdown` and it will create a separate menu item on the top in the documentation website

more details here: https://pkgdown.r-lib.org/articles/customise.html#:~:text=built%2Din%20components%3A-,intro,-%3A%20%E2%80%9CGet%20Started%E2%80%9D%2C%20which

Example: 
![image](https://user-images.githubusercontent.com/12943682/202404016-5117decf-16a8-42d2-885c-a59a69d01a3d.png)
because of this: https://github.com/tidyverse/dplyr/blob/main/vignettes/dplyr.Rmd

**Comment by rossfarrugia** [comment]
FYI @harriscw
