### ISSUE TITLE
Create vignette to cover the `covid_df` input in the run_all_checks report program

### ISSUE THREAD

**Issue by sarabodach** [pharmaverse/sdtmchecks#234]
> 2. Does `covid_df` need to be loaded in before running `run_all_checks`?

Yes and as an end user of the package its currently easy to not realize this.  This is why these messages are added.  Additionally, for `run_all_checks` parameter calls are controlled by `metads` parameter passed to the function, specifically `metads$fxn_in`.  I'm thinking we could update `covid_df=` parameters in these functions to expect a vector of terms instead of manipulating a data frame, I think that would make things easier and more intuitive on end users.  A vignette update showing how to pass covid terms to `run_all_checks` would probably be helpful.

_Originally posted by @harriscw in https://github.com/pharmaverse/sdtmchecks/issues/233#issuecomment-1697438132_

**Comment by harriscw** [comment]
Closing this as `covid_df` is being deprecated  CC @sarabodach
