### ISSUE TITLE
check_lb_missing_month - include extra param in metadata and in check? 

### ISSUE THREAD

**Issue by sarabodach** [pharmaverse/sdtmchecks#283]
The checks check_lb_missing_month and check_mh_missing_month do not have preproc=roche_derive_rave_row; however, check_pr_missing_month, check_cm_missing_month do.

**Comment by harriscw** [comment]
@sarabodach I assume this still needs to be updated.  If so I think it'd be good for @AlcJ123

**Comment by harriscw** [comment]
@AlcJ123 see `check_ae_aedecod` as an example.  Can you add in functioality around `roche_derive_rave_row` similar to `check_ae_aedecod`?

Note lines 6,7,48,58 in `check_ae_aedecod`.  The `roche_derive_rave_row` function is in `R/roche_utils.R`
