### ISSUE TITLE
check_cm_missing_month

### ISSUE THREAD

**Issue by sarabodach** [pharmaverse/sdtmchecks#333]
- [x] Update return message, which currently has: `fail(paste("There are ",length(unique(mydf$USUBJID)),
                     " patients with a conmed date that has year and day present but missing month. ",sep=""),
               mydf)` to refer to `patient(s)`
- ~[ ] Include tests for NA~

**Comment by harriscw** [comment]
@sarabodach Can you elaborate on "Include tests for NA" here?  Do you want a unit test to see how the code handles empty dates?  Since we are specifically looking for suspicious instances where year and day are present I assume this check doent care much if the date is fully missing
