### ISSUE TITLE
CRAN-ification

### ISSUE THREAD

**Issue by harriscw** [pharmaverse/sdtmchecks#335]
Lets go through these links to make the package CRAN ready
- [link 1](https://r-pkgs.org/release.html)
- [link 2](https://github.com/DavisVaughan/extrachecks)

**Comment by laywang142** [comment]
Functions missing `@returns` (none of them were missing `@example`): 
- check_ae_aelat.R
- check_ae_death.R
- check_cm_cmlat.R
- check_cm_cmlat_prior_ocular.R
- check_dd_death_date.R 
- check_ds_dsdecod_death.R 
- check_ds_sc_strat.R
- check_ec_sc_lat.R
- check_ex_extrt_exoccur.R
- check_ex_visit.R
- check_oe_bcva_4m_vs_1m_req.R
- check_oe_bcva_tot_mismatch.R
- check_oe_sc_lat_count_fingers.R
- check_pr_prlat.R
- check_qs_qsdtc_after_dd.R
- check_sc_dm_eligcrit.R
- check_sc_dm_seyeselc.R
- check_tr_dup.R

**Comment by laywang142** [comment]
According to the Davis Vaughan extra checks, we should remove the words "functions to" from the description in the DESCRIPTION file as well as consider adding a few more sentences. [detailed description](https://github.com/DavisVaughan/extrachecks?tab=readme-ov-file#your-package-description-description-is-flagged)

**Comment by laywang142** [comment]
This was in the LICENSE.md file. Should it be updated?

![image](https://github.com/pharmaverse/sdtmchecks/assets/122498550/39b6c4b4-fae6-494f-91de-adfe8e57714d)

**Comment by laywang142** [comment]
NOTE: tried to update the README but I had trouble rendering the .rmd file to a .md file
