### ISSUE TITLE
check_rs_rsdtc_visit_ordinal_error subset then check

### ISSUE THREAD

**Issue by harriscw** [pharmaverse/sdtmchecks#422]
`check_rs_rsdtc_visit_ordinal_error` first checks if all `VISITNUM` is missing and refuses to perform the check if so.  It then filters to overall responses only. 

The check should be updated to do the filtering to overall responses first, then check if all `VISITNUM` is missing.  We found on one study it was the case that `RSTESTCD = OVRLRESP` had all visit missing but other RSTESTCD had visit mapped, causing issues.  Since we are only checking overall responses anyway lets subset first.

![image](https://github.com/user-attachments/assets/2e14f874-56ba-41a4-a8ce-dc49116b41ec)

**Comment by harriscw** [comment]
@AlcJ123 think you could maybe help out on this?

**Comment by harriscw** [comment]
Just kidding @sarabodach already tackled this

**Comment by sarabodach** [comment]
Hi @harriscw - I had updated the logic of the checks, but I did not update the unit tests. Maybe that could be a new issue to tackle?
